# Generated by Django 5.0.3 on 2024-03-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(max_length=1000, verbose_name='Новость'),
        ),
    ]
