# Generated by Django 5.0.3 on 2024-04-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_time',
        ),
    ]
